tap "homebrew/services"
brew "ffmpeg"
brew "go"
brew "jq"
brew "mas"
brew "openssl@3"
brew "ripgrep"
brew "terminal-notifier"
brew "uv"
brew "zlib"
cask "affinity"
cask "alt-tab"
cask "appcleaner"
cask "arduino-ide"
cask "arc"
cask "bitwarden"
cask "claude-code"
cask "devpod"
cask "discord"
cask "displaylink"
cask "github"
cask "google-chrome"
cask "hiddenbar"
cask "keycastr"
cask "linearmouse"
cask "notchnook"
cask "obs"
cask "orbstack"
cask "raycast"
cask "rider"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "unity-hub"
cask "visual-studio-code"
cask "warp"
cask "zed"


mas "Amphetamine", id: 937984704
mas "RunCat", id: 1429033973
