[general]
animation_duration = 0.25
animation_enabled = true
enhanced_ui_excluded = []
padding = 4

[hotkeys]
center = 'cmd+ctrl+c'
focus_down = 'cmd+opt+down'
focus_left = 'cmd+opt+left'
focus_right = 'cmd+opt+right'
focus_up = 'cmd+opt+up'
maximize = 'cmd+ctrl+return'
snap_bottom = 'cmd+ctrl+down'
snap_bottom_left = 'cmd+opt+shift+left'
snap_bottom_right = 'cmd+opt+shift+right'
snap_left = 'cmd+ctrl+left'
snap_right = 'cmd+ctrl+right'
snap_top = 'cmd+ctrl+up'
snap_top_left = 'cmd+ctrl+shift+left'
snap_top_right = 'cmd+ctrl+shift+right'

[[launch]]
bundle_id = 'com.hnc.Discord'
key = 'cmd+ctrl+d'

[[launch]]
bundle_id = 'com.unity3d.UnityEditor5.x'
key = 'cmd+ctrl+u'

[[launch]]
bundle_id = 'company.thebrowser.Browser'
key = 'cmd+ctrl+a'

[[launch]]
bundle_id = 'dev.warp.Warp-Stable'
key = 'cmd+ctrl+w'

[[launch]]
bundle_id = 'dev.zed.Zed'
key = 'cmd+ctrl+z'

[[launch]]
bundle_id = 'com.spotify.client'
key = 'cmd+ctrl+s'

[[launch]]
bundle_id = 'com.jetbrains.rider'
key = 'cmd+ctrl+r'

[[launch]]
bundle_id = 'com.github.GitHubClient'
key = 'cmd+ctrl+g'

[[launch]]
key = 'cmd+ctrl+m'
path = '~/Documents/GitHub/melchior/build/melchior_main'