[general]
animation_duration = 0.25
animation_enabled = true
enhanced_ui_excluded = []
padding = 5

[hotkeys]
center = 'cmd+ctrl+c'
maximize = 'cmd+ctrl+return'
snap_bottom = 'cmd+ctrl+down'
snap_bottom_left = 'cmd+opt+shift+left'
snap_bottom_right = 'cmd+opt+shift+right'
snap_left = 'cmd+ctrl+left'
snap_right = 'cmd+ctrl+right'
snap_top = 'cmd+ctrl+up'

[[launch]]
bundle_id = 'com.hnc.Discord'
key = 'cmd+ctrl+d'

[[launch]]
bundle_id = 'com.unity3d.UnityEditor5.x'
key = 'cmd+ctrl+u'

[[launch]]
bundle_id = 'company.thebrowser.Browser'
key = 'cmd+ctrl+a'

[[launch]]
bundle_id = 'com.mitchellh.ghostty'
key = 'cmd+ctrl+w'

[[launch]]
bundle_id = 'dev.zed.Zed'
key = 'cmd+ctrl+z'

[[launch]]
bundle_id = 'com.spotify.client'
key = 'cmd+ctrl+s'

[[launch]]
bundle_id = 'com.jetbrains.rider'
key = 'cmd+ctrl+r'

[[launch]]
bundle_id = 'com.github.GitHubClient'
key = 'cmd+ctrl+g'

[[launch]]
path = '~/Documents/GitHub/melchior/build/melchior_main'
key = 'cmd+ctrl+m'

