
[[Snippets]]
  Description = "C#スクリプトの行数をカウントする"
  Output = ""
  Tag = []
  command = "find . -name \"*.cs\" -print0 | xargs -0 wc -l"

[[Snippets]]
  Description = "melchiorのビルドと起動(python3.12を指定)"
  Output = ""
  Tag = []
  command = "cmake .. -GNinja -DMELCHIOR_TUTORIALS=OFF -DMELCHIOR_EXAMPLES=ON -DMELCHIOR_BINDING=ON -DPython_EXECUTABLE=/etc/profiles/per-user/shuya.izumi/bin/python3.12 && ninja melchior_main -j8 && ninja toadflax && ./melchior_main"

[[Snippets]]
  Description = "NixでMac環境をrebuildする"
  Output = ""
  Tag = []
  command = "sudo darwin-rebuild switch --flake ."

[[Snippets]]
  Description = "melchiorビルド(nix環境)"
  Output = ""
  Tag = []
  command = "ninja melchior_main toadflax -j8 && ./melchior_main"

[[Snippets]]
  Description = "git blobless clone"
  Output = ""
  Tag = []
  command = "git clone --filter=blob:none https://github.com/void2610/hoge.git"

[[Snippets]]
  Description = "git サブモジュールのクローン"
  Output = ""
  Tag = []
  command = "git submodule update --init --recursive"
